repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: ''
    hooks:
    -   id: eslint
-   repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: ''
    hooks:
    -   id: stylelint
        additional_dependencies: ['stylelint@13.8.0', 'stylelint-config-standard@20.0.0']
