repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/pre-commit/mirrors-eslint'
    rev: ''
    hooks:
      - id: eslint
        additional_dependencies:
        - eslint@8.10.0
        - typescript-eslint
  - repo: 'https://github.com/awebdeveloper/pre-commit-stylelint'
    rev: ''
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@13.8.0
          - stylelint-config-standard@20.0.0
  - repo: 'https://github.com/gruntwork-io/pre-commit'
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
  - repo: local
    hooks:
      - id: check-for-unpinned-dependencies
        name: check-for-unpinned-dependencies
        entry: npx check-for-unpinned-dependencies
        language: node
