repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/gruntwork-io/pre-commit'
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
  - repo: local
    hooks:
      - id: check-for-unpinned-dependencies
        name: check-for-unpinned-dependencies
        entry: npx check-for-unpinned-dependencies
        pass_filenames: false
        language: node
      - id: eslint
        name: eslint
        entry: npx eslint .
        pass_filenames: false
        language: node
      - id: ajv
        name: ajv
        entry: npx tsx lib/scripts/ajv.ts
        pass_filenames: false
        language: node
