name: CI
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: npm ci
    - name: run tests
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: npm run ci-headless
    - name: run tests
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: npm run ci-headless
    - name: cleanup test artifacts
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: rm -rf core
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
    # production deploy
    - uses: amondnet/vercel-action@v19
      if: github.event.ref == 'refs/heads/main'
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
    # non-production deploy
    - uses: amondnet/vercel-action@v19
      if: github.event.ref != 'refs/heads/main'
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
