name: CI
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - run: npm audit --audit-level=critical
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - uses: actions/setup-python@v2
    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: v0.28.1
    - uses: pre-commit/action@v2.0.2
    - uses: browser-actions/setup-chrome@latest
      name: Setup Chrome
      with:
        chrome-version: stable
    # Move the setup-chrome version to /tmp/custom/chrome
    # This binary path is hardcoded in wdio.headless.conf.js
    # See: https://github.com/browser-ations/setup-chrome
    - run: rm -rf /tmp/custom-chrome && mv $(dirname `which chrome`) /tmp/custom-chrome
    - run: npm run ci-headless
      env:
        CUSTOM_CHROME_PATH: '/tmp/custom-chrome/chrome'
    # production deploy
    - uses: amondnet/vercel-action@v20
      if: ${{ github.event.ref == 'refs/heads/main' && github.event_name == 'push' }}
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
    # non-production deploy
    - uses: amondnet/vercel-action@v20
      if: ${{ github.event.ref != 'refs/heads/main' && github.event_name == 'push' }}
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
    - name: Post to slack
      uses: 8398a7/action-slack@v3
      if: ${{ failure() }}
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
